language: node_js
node_js:
  - "5"
android:
  components:
    - build-tools-18.1.1
    - android-18
    - extra
sudo: false
install:
    - npm install
script:
    - npm run build
    - npm run test
addons:
  artifacts:
    paths:
    - "platforms/android/build/outputs/apk"
after_success:
  - npm install -g cordova
  - cordova platform update android
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - npm run build:apk
  - mv platforms/android/build/outputs/apk/android-debug.apk platforms/android/build/outputs/apk/ReduxHybridApp.apk
